// Generated by `wit-bindgen` 0.41.0. DO NOT EDIT!
// Options used:
//   * runtime_path: "wit_bindgen_rt"
#[rustfmt::skip]
#[allow(dead_code, clippy::all)]
pub mod demo {
    pub mod policy {
        #[allow(dead_code, async_fn_in_trait, unused_imports, clippy::all)]
        pub mod types {
            #[used]
            #[doc(hidden)]
            static __FORCE_SECTION_REF: fn() = super::super::super::__link_custom_section_describing_imports;
            use super::super::super::_rt;
            /// One HTTP header. Names may repeat.
            #[derive(Clone)]
            pub struct Header {
                pub name: _rt::String,
                pub value: _rt::String,
            }
            impl ::core::fmt::Debug for Header {
                fn fmt(
                    &self,
                    f: &mut ::core::fmt::Formatter<'_>,
                ) -> ::core::fmt::Result {
                    f.debug_struct("Header")
                        .field("name", &self.name)
                        .field("value", &self.value)
                        .finish()
                }
            }
            /// The request the host passes to the guest.
            #[derive(Clone)]
            pub struct Request {
                pub method: _rt::String,
                /// "GET", "POST"
                pub path: _rt::String,
                /// "/orders/42"
                pub headers: _rt::Vec<Header>,
            }
            impl ::core::fmt::Debug for Request {
                fn fmt(
                    &self,
                    f: &mut ::core::fmt::Formatter<'_>,
                ) -> ::core::fmt::Result {
                    f.debug_struct("Request")
                        .field("method", &self.method)
                        .field("path", &self.path)
                        .field("headers", &self.headers)
                        .finish()
                }
            }
            #[derive(Clone)]
            pub struct Rejection {
                pub status: u16,
                /// 401, 429
                pub message: _rt::String,
            }
            impl ::core::fmt::Debug for Rejection {
                fn fmt(
                    &self,
                    f: &mut ::core::fmt::Formatter<'_>,
                ) -> ::core::fmt::Result {
                    f.debug_struct("Rejection")
                        .field("status", &self.status)
                        .field("message", &self.message)
                        .finish()
                }
            }
            /// What the gateway does with the request.
            #[derive(Clone)]
            pub enum Decision {
                /// Forward to the backend.
                Allow,
                /// Reject with this status and message.
                Reject(Rejection),
            }
            impl ::core::fmt::Debug for Decision {
                fn fmt(
                    &self,
                    f: &mut ::core::fmt::Formatter<'_>,
                ) -> ::core::fmt::Result {
                    match self {
                        Decision::Allow => f.debug_tuple("Decision::Allow").finish(),
                        Decision::Reject(e) => {
                            f.debug_tuple("Decision::Reject").field(e).finish()
                        }
                    }
                }
            }
        }
    }
}
#[rustfmt::skip]
#[allow(dead_code, clippy::all)]
pub mod exports {
    pub mod demo {
        pub mod policy {
            /// What the guest sees and does.
            #[allow(dead_code, async_fn_in_trait, unused_imports, clippy::all)]
            pub mod handler {
                #[used]
                #[doc(hidden)]
                static __FORCE_SECTION_REF: fn() = super::super::super::super::__link_custom_section_describing_imports;
                use super::super::super::super::_rt;
                pub type Request = super::super::super::super::demo::policy::types::Request;
                pub type Decision = super::super::super::super::demo::policy::types::Decision;
                #[doc(hidden)]
                #[allow(non_snake_case)]
                pub unsafe fn _export_on_request_cabi<T: Guest>(
                    arg0: *mut u8,
                    arg1: usize,
                    arg2: *mut u8,
                    arg3: usize,
                    arg4: *mut u8,
                    arg5: usize,
                ) -> *mut u8 {
                    #[cfg(target_arch = "wasm32")] _rt::run_ctors_once();
                    let len0 = arg1;
                    let bytes0 = _rt::Vec::from_raw_parts(arg0.cast(), len0, len0);
                    let len1 = arg3;
                    let bytes1 = _rt::Vec::from_raw_parts(arg2.cast(), len1, len1);
                    let base8 = arg4;
                    let len8 = arg5;
                    let mut result8 = _rt::Vec::with_capacity(len8);
                    for i in 0..len8 {
                        let base = base8
                            .add(i * (4 * ::core::mem::size_of::<*const u8>()));
                        let e8 = {
                            let l2 = *base.add(0).cast::<*mut u8>();
                            let l3 = *base
                                .add(::core::mem::size_of::<*const u8>())
                                .cast::<usize>();
                            let len4 = l3;
                            let bytes4 = _rt::Vec::from_raw_parts(l2.cast(), len4, len4);
                            let l5 = *base
                                .add(2 * ::core::mem::size_of::<*const u8>())
                                .cast::<*mut u8>();
                            let l6 = *base
                                .add(3 * ::core::mem::size_of::<*const u8>())
                                .cast::<usize>();
                            let len7 = l6;
                            let bytes7 = _rt::Vec::from_raw_parts(l5.cast(), len7, len7);
                            super::super::super::super::demo::policy::types::Header {
                                name: _rt::string_lift(bytes4),
                                value: _rt::string_lift(bytes7),
                            }
                        };
                        result8.push(e8);
                    }
                    _rt::cabi_dealloc(
                        base8,
                        len8 * (4 * ::core::mem::size_of::<*const u8>()),
                        ::core::mem::size_of::<*const u8>(),
                    );
                    let result9 = T::on_request(super::super::super::super::demo::policy::types::Request {
                        method: _rt::string_lift(bytes0),
                        path: _rt::string_lift(bytes1),
                        headers: result8,
                    });
                    let ptr10 = (&raw mut _RET_AREA.0).cast::<u8>();
                    use super::super::super::super::demo::policy::types::Decision as V13;
                    match result9 {
                        V13::Allow => {
                            *ptr10.add(0).cast::<u8>() = (0i32) as u8;
                        }
                        V13::Reject(e) => {
                            *ptr10.add(0).cast::<u8>() = (1i32) as u8;
                            let super::super::super::super::demo::policy::types::Rejection {
                                status: status11,
                                message: message11,
                            } = e;
                            *ptr10
                                .add(::core::mem::size_of::<*const u8>())
                                .cast::<u16>() = (_rt::as_i32(status11)) as u16;
                            let vec12 = (message11.into_bytes()).into_boxed_slice();
                            let ptr12 = vec12.as_ptr().cast::<u8>();
                            let len12 = vec12.len();
                            ::core::mem::forget(vec12);
                            *ptr10
                                .add(3 * ::core::mem::size_of::<*const u8>())
                                .cast::<usize>() = len12;
                            *ptr10
                                .add(2 * ::core::mem::size_of::<*const u8>())
                                .cast::<*mut u8>() = ptr12.cast_mut();
                        }
                    }
                    ptr10
                }
                #[doc(hidden)]
                #[allow(non_snake_case)]
                pub unsafe fn __post_return_on_request<T: Guest>(arg0: *mut u8) {
                    let l0 = i32::from(*arg0.add(0).cast::<u8>());
                    match l0 {
                        0 => {}
                        _ => {
                            let l1 = *arg0
                                .add(2 * ::core::mem::size_of::<*const u8>())
                                .cast::<*mut u8>();
                            let l2 = *arg0
                                .add(3 * ::core::mem::size_of::<*const u8>())
                                .cast::<usize>();
                            _rt::cabi_dealloc(l1, l2, 1);
                        }
                    }
                }
                pub trait Guest {
                    /// The host calls this once per API request. The guest reads the
                    /// request and returns what the gateway should do.
                    fn on_request(req: Request) -> Decision;
                }
                #[doc(hidden)]
                macro_rules! __export_demo_policy_handler_0_1_0_cabi {
                    ($ty:ident with_types_in $($path_to_types:tt)*) => {
                        const _ : () = { #[unsafe (export_name =
                        "demo:policy/handler@0.1.0#on-request")] unsafe extern "C" fn
                        export_on_request(arg0 : * mut u8, arg1 : usize, arg2 : * mut u8,
                        arg3 : usize, arg4 : * mut u8, arg5 : usize,) -> * mut u8 {
                        unsafe { $($path_to_types)*:: _export_on_request_cabi::<$ty >
                        (arg0, arg1, arg2, arg3, arg4, arg5) } } #[unsafe (export_name =
                        "cabi_post_demo:policy/handler@0.1.0#on-request")] unsafe extern
                        "C" fn _post_return_on_request(arg0 : * mut u8,) { unsafe {
                        $($path_to_types)*:: __post_return_on_request::<$ty > (arg0) } }
                        };
                    };
                }
                #[doc(hidden)]
                pub(crate) use __export_demo_policy_handler_0_1_0_cabi;
                #[cfg_attr(target_pointer_width = "64", repr(align(8)))]
                #[cfg_attr(target_pointer_width = "32", repr(align(4)))]
                struct _RetArea(
                    [::core::mem::MaybeUninit<
                        u8,
                    >; 4 * ::core::mem::size_of::<*const u8>()],
                );
                static mut _RET_AREA: _RetArea = _RetArea(
                    [::core::mem::MaybeUninit::uninit(); 4
                        * ::core::mem::size_of::<*const u8>()],
                );
            }
        }
    }
}
#[rustfmt::skip]
mod _rt {
    #![allow(dead_code, clippy::all)]
    pub use alloc_crate::string::String;
    pub use alloc_crate::vec::Vec;
    #[cfg(target_arch = "wasm32")]
    pub fn run_ctors_once() {
        wit_bindgen_rt::run_ctors_once();
    }
    pub unsafe fn string_lift(bytes: Vec<u8>) -> String {
        if cfg!(debug_assertions) {
            String::from_utf8(bytes).unwrap()
        } else {
            String::from_utf8_unchecked(bytes)
        }
    }
    pub unsafe fn cabi_dealloc(ptr: *mut u8, size: usize, align: usize) {
        if size == 0 {
            return;
        }
        let layout = alloc::Layout::from_size_align_unchecked(size, align);
        alloc::dealloc(ptr, layout);
    }
    pub fn as_i32<T: AsI32>(t: T) -> i32 {
        t.as_i32()
    }
    pub trait AsI32 {
        fn as_i32(self) -> i32;
    }
    impl<'a, T: Copy + AsI32> AsI32 for &'a T {
        fn as_i32(self) -> i32 {
            (*self).as_i32()
        }
    }
    impl AsI32 for i32 {
        #[inline]
        fn as_i32(self) -> i32 {
            self as i32
        }
    }
    impl AsI32 for u32 {
        #[inline]
        fn as_i32(self) -> i32 {
            self as i32
        }
    }
    impl AsI32 for i16 {
        #[inline]
        fn as_i32(self) -> i32 {
            self as i32
        }
    }
    impl AsI32 for u16 {
        #[inline]
        fn as_i32(self) -> i32 {
            self as i32
        }
    }
    impl AsI32 for i8 {
        #[inline]
        fn as_i32(self) -> i32 {
            self as i32
        }
    }
    impl AsI32 for u8 {
        #[inline]
        fn as_i32(self) -> i32 {
            self as i32
        }
    }
    impl AsI32 for char {
        #[inline]
        fn as_i32(self) -> i32 {
            self as i32
        }
    }
    impl AsI32 for usize {
        #[inline]
        fn as_i32(self) -> i32 {
            self as i32
        }
    }
    extern crate alloc as alloc_crate;
    pub use alloc_crate::alloc;
}
/// Generates `#[unsafe(no_mangle)]` functions to export the specified type as
/// the root implementation of all generated traits.
///
/// For more information see the documentation of `wit_bindgen::generate!`.
///
/// ```rust
/// # macro_rules! export{ ($($t:tt)*) => (); }
/// # trait Guest {}
/// struct MyType;
///
/// impl Guest for MyType {
///     // ...
/// }
///
/// export!(MyType);
/// ```
#[allow(unused_macros)]
#[doc(hidden)]
macro_rules! __export_policy_impl {
    ($ty:ident) => {
        self::export!($ty with_types_in self);
    };
    ($ty:ident with_types_in $($path_to_types_root:tt)*) => {
        $($path_to_types_root)*::
        exports::demo::policy::handler::__export_demo_policy_handler_0_1_0_cabi!($ty
        with_types_in $($path_to_types_root)*:: exports::demo::policy::handler);
    };
}
#[doc(inline)]
pub(crate) use __export_policy_impl as export;
#[cfg(target_arch = "wasm32")]
#[unsafe(
    link_section = "component-type:wit-bindgen:0.41.0:demo:policy@0.1.0:policy:encoded world"
)]
#[doc(hidden)]
#[allow(clippy::octal_escapes)]
pub static __WIT_BINDGEN_COMPONENT_TYPE: [u8; 451] = *b"\
\0asm\x0d\0\x01\0\0\x19\x16wit-component-encoding\x04\0\x07\xc6\x02\x01A\x02\x01\
A\x06\x01B\x09\x01r\x02\x04names\x05values\x04\0\x06header\x03\0\0\x01p\x01\x01r\
\x03\x06methods\x04paths\x07headers\x02\x04\0\x07request\x03\0\x03\x01r\x02\x06s\
tatus{\x07messages\x04\0\x09rejection\x03\0\x05\x01q\x02\x05allow\0\0\x06reject\x01\
\x06\0\x04\0\x08decision\x03\0\x07\x03\0\x17demo:policy/types@0.1.0\x05\0\x02\x03\
\0\0\x07request\x02\x03\0\0\x08decision\x01B\x06\x02\x03\x02\x01\x01\x04\0\x07re\
quest\x03\0\0\x02\x03\x02\x01\x02\x04\0\x08decision\x03\0\x02\x01@\x01\x03req\x01\
\0\x03\x04\0\x0aon-request\x01\x04\x04\0\x19demo:policy/handler@0.1.0\x05\x03\x04\
\0\x18demo:policy/policy@0.1.0\x04\0\x0b\x0c\x01\0\x06policy\x03\0\0\0G\x09produ\
cers\x01\x0cprocessed-by\x02\x0dwit-component\x070.227.1\x10wit-bindgen-rust\x06\
0.41.0";
#[inline(never)]
#[doc(hidden)]
pub fn __link_custom_section_describing_imports() {
    wit_bindgen_rt::maybe_link_cabi_realloc();
}
